# Generated by Django 2.2.7 on 2019-11-09 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20191109_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='user',
            new_name='student',
        ),
    ]
