# Generated by Django 2.2.7 on 2019-11-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20191109_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentenrollment',
            old_name='course',
            new_name='course_shift',
        ),
    ]
