# Generated by Django 2.2.4 on 2019-08-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0004_auto_20190803_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='shift',
        ),
        migrations.AddField(
            model_name='course',
            name='shifts',
            field=models.ManyToManyField(related_name='courses', to='enquiry.Shift'),
        ),
    ]
