# Generated by Django 2.2.7 on 2019-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0005_auto_20191109_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
