# Generated by Django 2.2.7 on 2019-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0007_auto_20191109_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
